Repository SanjitSai/Hacktoberfest-22, pull requests merged in 2022-10, with the labels that each got.

#18 Added merge lists program in Python
  solutions/merge_list.py
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#23 levelOrder.py
  levelOrder.py
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#28 added solution to finding second largest element in an array
  ExtraQuestions/Problems/secondLargestElement.cpp
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted

#30 cpp solution for computing fibonacci number using pre-computation
  solutions/fibbonacci_number.cpp
Labels: hacktoberfest2022, hacktoberfest, hacktoberfest-accepted, hacktoberfest22-accepted

#31 added 01_Knapsack.cpp
  01_Knapsack.cpp
Labels: hacktoberfest
